routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Auth::routes();

Route::group([
    'domain' => 'admin.' . config('app.short_url'),
    'namespace' => 'Auth',
    'as' => 'auth.'
], function () {

    Route::get('/login', 'LoginController@showAdminLoginForm')->name('login.admin');
    Route::get('/register', 'RegisterController@showAdminRegisterForm')->name('register.admin');

});

Route::group([
    'domain' => 'admin.' . config('app.short_url'),
    'namespace' => 'Admin',
    'as' => 'admin.'
], function () {

    Route::get('/dashboard', 'DashboardController@index')->name('dashboard');

    Route::group([
        'prefix' => '/users',
        'as' => 'users.'
    ], function () {

        Route::get('/', 'UserController@index')->name('index');
        Route::post('/search', 'UserController@search')->name('search');

    });

    Route::group([
        'prefix' => '/books',
        'as' => 'books.'
    ], function () {

        Route::get('/', 'BookController@index')->name('index');
        Route::post('/search', 'BookController@search')->name('search');

    });

    Route::resource('/categories', 'CategoryController');
    Route::group([
        'prefix' => '/categories',
        'as' => 'categories.'
    ], function () {

        Route::post('/search', 'CategoryController@search')->name('search');

    });

    Route::resource('/languages', 'LanguageController');
    Route::group([
        'prefix' => '/languages',
        'as' => 'languages.'
    ], function () {

        Route::post('/search', 'LanguageController@search')->name('search');

    });

});

Route::get('/', 'HomeController@index')->name('home');
Route::get('/search', 'SearchController@index')->name('search');
Route::get('/faq', 'FaqController@index')->name('faq');
Route::get('/{slug}/read', 'PageController@index')->name('pages.detail');
Route::get('/set-language/{locale}', 'LocalizationController@setLanguage')->name('languages.set');

Route::middleware('auth:admin,writer')->get('/profiles', 'ProfileController@index')->name('profiles.index');
Route::middleware('auth:writer,admin')->get('/profiles/edit', 'ProfileController@edit')->name('profiles.edit');
Route::get('/profiles/{id}', 'ProfileController@show')->name('profiles.show');

Route::post('/search', 'SearchController@search')->name('search.form');

Route::group([
    'namespace' => 'Auth',
    'as' => 'auth.'
], function () {


    Route::post('/logout', 'LoginController@logout')->name('logout');

    Route::group([
        'prefix' => '/login',
        'as' => 'login.'
    ], function () {

        Route::get('/', 'LoginController@showWriterLoginForm')->name('writer');
        Route::post('/{role}', 'LoginController@login')->name('form');

    });

    Route::group([
        'prefix' => '/register',
        'as' => 'register.'
    ], function () {

        Route::get('/', 'RegisterController@showWriterRegisterForm')->name('writer');
        Route::post('/{role}', 'RegisterController@register')->name('form');

    });

});

Route::group([
    'namespace' => 'Auth',
    'as' => 'password.'
], function () {

    Route::get('/forgot-password', 'ForgotPasswordController@showLinkRequestForm')->name('request');
    Route::get('/reset-password/{token}', 'ResetPasswordController@showResetForm')->name('reset');

    Route::post('/password/email', 'ForgotPasswordController@sendResetLinkEmail')->name('email');
    Route::post('/password/reset', 'ResetPasswordController@reset')->name('update');

});

Route::group([
    'namespace' => 'Writer',
    'as' => 'writer.'
], function () {

    Route::get('/archives', 'ArchiveController@index')->name('archives');

    Route::get('/all-books', 'BookController@index')->name('books');
    Route::group([
        'prefix' => '/books',
        'as' => 'books.'
    ], function () {

        Route::get('/create', 'BookController@create')->name('create');
        Route::get('/{id}/edit-info', 'BookController@edit')->name('edit');
        Route::get('/{id}', 'BookController@detail')->name('detail');
        Route::get('/add-pages/{id}', 'BookController@addPages')->name('add_pages');

        Route::post('/', 'BookController@store')->name('store');
        Route::post('/search', 'BookController@search')->name('search');
        Route::put('/update/{id}', 'BookController@update')->name('update');
        Route::post('/restore/{id}', 'BookController@restore')->name('restore');
        Route::delete('/{id}', 'BookController@destroy')->name('destroy');
        Route::delete('/force-delete/{id}', 'BookController@forceDelete')->name('force_delete');

    });

    Route::get('/all-pages', 'PageController@index')->name('pages');
    Route::get('/{slug}/edit', 'PageController@edit')->name('pages.edit');
    Route::group([
        'prefix' => '/pages',
        'as' => 'pages.'
    ], function () {

        Route::post('/create', 'PageController@create')->name('create');
        Route::post('/search', 'PageController@search')->name('search');
        Route::put('/update/{id}', 'PageController@update')->name('update');
        Route::post('/restore/{id}', 'PageController@restore')->name('restore');
        Route::delete('/{id}', 'PageController@destroy')->name('destroy');
        Route::delete('/force-delete/{id}', 'PageController@forceDelete')->name('force_delete');

    });

});

Route::post('/uploads/image', 'FileUploadController@uploadImage')->name('uploads.image');

Route::fallback('ErrorController@notFound')->name('not_found');

resources/views/pages/writer/page/edit/index.blade.php
@extends('layouts.dashboard_app', [
    'page_key' => 'page-new',
    'form_route' => route('writer.pages.update', $page->id),
    'form_method' => 'put'
])

@section('content')
    <div class="kt-portlet kt-portlet--tabs">
        <div class="kt-portlet__head">
            <div class="kt-portlet__head-toolbar">

                @include('menu.page_create-tabs')

            </div>
        </div>
        <div class="kt-portlet__body">
            <div class="tab-content  kt-margin-t-20">
                @if($errors->any())
                <div class="text-danger mb-5">
                    <h4>Invalid Input:</h4>
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{$error}}</li>
                        @endforeach
                    </ul>
                </div>
                @endif
                {{-- Page Details Tab Content --}}
                @include('pages.writer.page.edit.page_details')

                {{-- Page Content Tab Content --}}
                @include('pages.writer.page.edit.page_content')

            </div>
        </div>
    </div>
@stop

@section('subheader-main')
    <h3 class="kt-subheader__title">
        Page Editor
    </h3>
    <span class="kt-subheader__separator kt-subheader__separator--v"></span>
    <div class="kt-subheader__group" id="kt_subheader_search">
        <span class="kt-subheader__desc" id="kt_subheader_total">
            {{ $page->page_name }}
        </span>
    </div>
@stop

@section('subheader-toolbar')
    <div class="btn-group">
        <button type="submit" class="btn btn-brand btn-bold">
            Save Changes
        </button>
    </div>
@stop

resources/views/pages/writer/page/edit/page_content.blade.php
<div class="tab-pane active" id="pageContentTab" role="tabpanel">
    <div class="kt-form kt-form--label-right">
        <div class="kt-form__body">

            <div class="kt-section">
                <div class="kt-section__body">
                    <div class="form-group row">
                        <label class="col-xl-3 col-lg-3 col-form-label">Page Heading</label>
                        <div class="col-lg-9 col-xl-6">
                            <input name="heading" class="form-control" type="text" value="{{ $page->heading }}">
                        </div>
                    </div>
                </div>
            </div>

            <div
                class="kt-separator kt-separator--border-dashed kt-separator--portlet-fit kt-separator--space-lg"></div>

            <div class="kt-section kt-section--first">
                <div class="kt-section__body">
                    <div class="row mx-2">
                        <h3 class="kt-section__title kt-section__title-sm">Content:</h3>
                        <textarea name="inputContent">{{ $page->content }}</textarea>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@push('scripts')
    <script src="{{ asset('vendor/ckeditor/ckeditor.js') }}"></script>
    <script>
        $(document).ready(function () {
            CKEDITOR.replace('inputContent');
        });
    </script>
@endpush

resources/views/pages/writer/page/edit/page_details.blade.php
<div class="tab-pane" id="pageDetailsTab" role="tabpanel">
    <div class="kt-form kt-form--label-right">
        <div class="kt-form__body">
            <div class="kt-section kt-section--first">
                <div class="kt-section__body">
                    <div class="row">
                        <label class="col-xl-3"></label>
                        <div class="col-lg-9 col-xl-6">
                            <h3 class="kt-section__title kt-section__title-sm">Page Info:</h3>
                        </div>
                    </div>

                    <div class="form-group row">
                        <label class="col-xl-3 col-lg-3 col-form-label">Page Name</label>
                        <div class="col-lg-9 col-xl-6">
                            <input name="page_name" class="form-control" type="text" value="{{ old('page_name') ? old('page_name') : $page->page_name }}">
                            <span class="form-text text-muted">If not specified, then it'll take the value of the page heading.</span>
                        </div>
                    </div>

                    <div class="form-group row">
                        <label class="col-xl-3 col-lg-3 col-form-label">Page Slug</label>
                        <div class="col-lg-9 col-xl-6">
                            <input name="slug" class="form-control" type="text" value="{{ old('slug') ? old('slug') : $page->slug }}">
                            <span class="form-text text-muted">* Slug only includes alphabets, numbers, dashes(-), and underscores(_)</span>
                            @error('slug')
                            <span class="form-text text-danger">{{ $message }}</span>
                            @enderror
                        </div>
                    </div>

                    <div class="form-group row">
                        <label class="col-xl-3 col-lg-3 col-form-label">Page Description (Optional)</label>
                        <div class="col-lg-9 col-xl-6">
                            <textarea
                                name="description"
                                class="form-control"
                                id="exampleTextarea"
                                rows="3" placeholder="Description...">{{ old('description') ? old('description') : $page->description }}</textarea>
                        </div>
                    </div>

                    <div class="row">
                        <label class="col-xl-3"></label>
                        <div class="col-lg-9 col-xl-6">
                            <h3 class="kt-section__title kt-section__title-sm">Access Control:</h3>
                        </div>
                    </div>

                    @php
                        $accesses = [
                            ['public', __('Public')],
                            ['private', __('Only Me')]
                        ];
                    @endphp

                    <div class="form-group row">
                        <label for="selectPageAccess" class="col-xl-3 col-lg-3 col-form-label">Page Access</label>
                        <div class="col-lg-9 col-xl-6">
                            <select name="access" id="selectPageAccess" class="form-control">
                                @foreach($accesses as $access)
                                    <option value="{{ $access[0] }}" @if($access[0] == $page->access) selected @endif>
                                        {{ $access[1] }}
                                    </option>
                                @endforeach
                            </select>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>
</div>