routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Auth::routes();

Route::group([
    'domain' => 'admin.' . config('app.short_url'),
    'namespace' => 'Auth',
    'as' => 'auth.'
], function () {

    Route::get('/login', 'LoginController@showAdminLoginForm')->name('login.admin');
    Route::get('/register', 'RegisterController@showAdminRegisterForm')->name('register.admin');

});

Route::group([
    'domain' => 'admin.' . config('app.short_url'),
    'namespace' => 'Admin',
    'as' => 'admin.'
], function () {

    Route::get('/dashboard', 'DashboardController@index')->name('dashboard');

    Route::group([
        'prefix' => '/users',
        'as' => 'users.'
    ], function () {

        Route::get('/', 'UserController@index')->name('index');
        Route::post('/search', 'UserController@search')->name('search');

    });

    Route::group([
        'prefix' => '/books',
        'as' => 'books.'
    ], function () {

        Route::get('/', 'BookController@index')->name('index');
        Route::post('/search', 'BookController@search')->name('search');

    });

    Route::resource('/categories', 'CategoryController');
    Route::group([
        'prefix' => '/categories',
        'as' => 'categories.'
    ], function () {

        Route::post('/search', 'CategoryController@search')->name('search');

    });

    Route::resource('/languages', 'LanguageController');
    Route::group([
        'prefix' => '/languages',
        'as' => 'languages.'
    ], function () {

        Route::post('/search', 'LanguageController@search')->name('search');

    });

});

Route::get('/', 'HomeController@index')->name('home');
Route::get('/search', 'SearchController@index')->name('search');
Route::get('/faq', 'FaqController@index')->name('faq');
Route::get('/{slug}/read', 'PageController@index')->name('pages.detail');
Route::get('/set-language/{locale}', 'LocalizationController@setLanguage')->name('languages.set');

Route::middleware('auth:admin,writer')->get('/profiles', 'ProfileController@index')->name('profiles.index');
Route::middleware('auth:writer,admin')->get('/profiles/edit', 'ProfileController@edit')->name('profiles.edit');
Route::get('/profiles/{id}', 'ProfileController@show')->name('profiles.show');

Route::post('/search', 'SearchController@search')->name('search.form');

Route::group([
    'namespace' => 'Auth',
    'as' => 'auth.'
], function () {


    Route::post('/logout', 'LoginController@logout')->name('logout');

    Route::group([
        'prefix' => '/login',
        'as' => 'login.'
    ], function () {

        Route::get('/', 'LoginController@showWriterLoginForm')->name('writer');
        Route::post('/{role}', 'LoginController@login')->name('form');

    });

    Route::group([
        'prefix' => '/register',
        'as' => 'register.'
    ], function () {

        Route::get('/', 'RegisterController@showWriterRegisterForm')->name('writer');
        Route::post('/{role}', 'RegisterController@register')->name('form');

    });

});

Route::group([
    'namespace' => 'Auth',
    'as' => 'password.'
], function () {

    Route::get('/forgot-password', 'ForgotPasswordController@showLinkRequestForm')->name('request');
    Route::get('/reset-password/{token}', 'ResetPasswordController@showResetForm')->name('reset');

    Route::post('/password/email', 'ForgotPasswordController@sendResetLinkEmail')->name('email');
    Route::post('/password/reset', 'ResetPasswordController@reset')->name('update');

});

Route::group([
    'namespace' => 'Writer',
    'as' => 'writer.'
], function () {

    Route::get('/archives', 'ArchiveController@index')->name('archives');

    Route::get('/all-books', 'BookController@index')->name('books');
    Route::group([
        'prefix' => '/books',
        'as' => 'books.'
    ], function () {

        Route::get('/create', 'BookController@create')->name('create');
        Route::get('/{id}/edit-info', 'BookController@edit')->name('edit');
        Route::get('/{id}', 'BookController@detail')->name('detail');
        Route::get('/add-pages/{id}', 'BookController@addPages')->name('add_pages');

        Route::post('/', 'BookController@store')->name('store');
        Route::post('/search', 'BookController@search')->name('search');
        Route::put('/update/{id}', 'BookController@update')->name('update');
        Route::post('/restore/{id}', 'BookController@restore')->name('restore');
        Route::delete('/{id}', 'BookController@destroy')->name('destroy');
        Route::delete('/force-delete/{id}', 'BookController@forceDelete')->name('force_delete');

    });

    Route::get('/all-pages', 'PageController@index')->name('pages');
    Route::get('/{slug}/edit', 'PageController@edit')->name('pages.edit');
    Route::group([
        'prefix' => '/pages',
        'as' => 'pages.'
    ], function () {

        Route::post('/create', 'PageController@create')->name('create');
        Route::post('/search', 'PageController@search')->name('search');
        Route::put('/update/{id}', 'PageController@update')->name('update');
        Route::post('/restore/{id}', 'PageController@restore')->name('restore');
        Route::delete('/{id}', 'PageController@destroy')->name('destroy');
        Route::delete('/force-delete/{id}', 'PageController@forceDelete')->name('force_delete');

    });

});

Route::post('/uploads/image', 'FileUploadController@uploadImage')->name('uploads.image');

Route::fallback('ErrorController@notFound')->name('not_found');

app/Models/Book.php
<?php

namespace App\Models;

use App\Scopes\FilterScope;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Support\Carbon;
use Illuminate\Support\Facades\Auth;

class Book extends Model
{
    use SoftDeletes;

    protected $fillable = [
        'book_name',
        'writer_id',
        'language_id',
        'cover_image',
        'access',
        'first_page',
        'description'
    ];

    protected $attributes = [
        'description' => '',
    ];

    protected static function booted()
    {
        static::addGlobalScope(new FilterScope('book_name'));
    }

    public function writer()
    {
        return $this->belongsTo(User::class, 'writer_id');
    }

    public function categories()
    {
        return $this->belongsToMany(Category::class, 'category_book');
    }

    public function pages()
    {
        return $this->hasMany('App\Models\Page');
    }

    public function getCoverImageUrlAttribute()
    {
        return
            $this->cover_image
                ? asset('storage/' . $this->cover_image)
                : asset('media/book-cover-placeholder.png');
    }

    public function getUpdatedAtAttribute($updated_at)
    {
        return Carbon::parse($updated_at, config('app.timezone'))
            ->setTimezone('GMT+7')
            ->format('d M Y');
    }

    public function scopeBelongsToUser(Builder $query, $userId = null)
    {
        if ($userId == null) {
            if (!($userId = Auth::id())) {
                return $query->where('writer_id', 1);
            }
        }
        return $query->where('writer_id', $userId);
    }

}

app/Models/Writer.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Notifications\Notifiable;

class Writer extends \Illuminate\Foundation\Auth\User
{
    use Notifiable;

    protected $table = 'users';

    protected $guard = 'writer';

    protected $fillable = [
        'name', 'email', 'password',
    ];

    protected $hidden = [
        'password', 'remember_token',
    ];

    protected $attributes = [
        'role' => 'writer'
    ];

}

app/Http/Controllers/Writer/ArchiveController.php
<?php

namespace App\Http\Controllers\Writer;

use App\Http\Controllers\Controller;
use App\Models\Book;
use App\Models\Page;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;

class ArchiveController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth:writer');
    }

    public function index()
    {
        $userId = auth('writer')->id();
        $archived_books = Book::select(
            DB::raw('"books" as type'),
            'id',
            'book_name as name',
            'deleted_at'
        )->where('writer_id', $userId)->onlyTrashed();
        $archived_items = Page::select(
            DB::raw('"pages" as type'),
            'id',
            'page_name as name',
            'deleted_at'
        )->where('writer_id', $userId)->onlyTrashed()
            ->union($archived_books)
            ->orderBy('deleted_at', 'DESC')
            ->paginate(10);
        return view('pages.writer.archives.index')
            ->with('items', $archived_items);
    }

}

app/Http/Controllers/Writer/BookController.php
<?php

namespace App\Http\Controllers\Writer;

use App\Http\Controllers\Controller;
use App\Http\Requests\Writer\CreateBookRequest;
use App\Http\Resources\BookResource;
use App\Http\Resources\PageResource;
use App\Models\Book;
use App\Models\Category;
use App\Models\Language;
use App\Models\Page;
use Illuminate\Http\Request;

class BookController extends Controller
{

    public function __construct()
    {
        $this->middleware('auth:writer');
    }

    public function index()
    {
        $books = Book::belongsToUser()
            ->select(['id', 'book_name', 'cover_image', 'description', 'updated_at'])
            ->orderBy('book_name')
            ->paginate(12);
        return view('pages.writer.books.index')
            ->with('books', BookResource::collection($books));
    }

    public function create()
    {
        return view('pages.writer.books.create')
            ->with([
                'categories' =>
                    Category::select(['id', 'category_name'])
                        ->orderBy('category_name')
                        ->get(),
                'languages' =>
                    Language::select(['id', 'language_name'])
                        ->orderBy('language_name')
                        ->get()
            ]);
    }

    public function store(CreateBookRequest $request)
    {
        $book = Book::create([
            'book_name' => $request->book_name,
            'writer_id' => auth()->id(),
            'language_id' => $request->language_id,
            'cover_image' => $request->cover_image,
            'access' => 'public',
        ]);
        $book->categories()->attach($request->input('category_id', []));
        return redirect()->route('writer.books.detail', $book->id);
    }

    public function detail($id)
    {
        $pages = Page::where('book_id', $id)
            ->select('id', 'page_name', 'slug', 'access', 'updated_at')
            ->paginate(10);
        return view('pages.writer.books.detail')
            ->with([
                'book' => Book::findOrFail($id),
                'pages' => PageResource::collection($pages)
            ]);
    }

    public function edit($id)
    {
        $book = Book::findOrFail($id);
        $selectedCategories = $book->categories->map(function ($category) {
            return $category->id;
        });
        return view('pages.writer.books.edit')
            ->with([
                'book' => $book,
                'selected_categories' => $selectedCategories,
                'categories' =>
                    Category::select(['id', 'category_name'])
                        ->orderBy('category_name')
                        ->get(),
                'languages' =>
                    Language::select(['id', 'language_name'])
                        ->orderBy('language_name')
                        ->get()
            ]);
    }

    public function update(CreateBookRequest $request, $id)
    {
        $attributes = $request->all();
        $book = Book::findOrFail($id);
        $book->update($attributes);
        $book->categories()->sync($request->input('category_id', []));
        return redirect()->route('writer.books.detail', $id);
    }

    public function addPages($id)
    {
        return view('pages.writer.books.add_page')
            ->with('book', Book::findOrFail($id));
    }

    public function search(Request $request)
    {
        return redirect()->route('writer.books', ['q' => $request->search]);
    }

    public function restore($id)
    {
        Book::withTrashed()->whereId($id)->restore();
        return redirect()->route('writer.archives');
    }

    public function destroy($id)
    {
        Book::destroy($id);
        return redirect()->route('writer.books');
    }

    public function forceDelete($id)
    {
        $book = Book::withTrashed()->whereId($id)->first();
        $book->pages()->update(['book_id' => null]);
        $book->forceDelete();
        return redirect()->route('writer.archives');
    }

}

app/Http/Controllers/Writer/PageController.php
<?php

namespace App\Http\Controllers\Writer;

use App\Http\Controllers\Controller;
use App\Http\Requests\Writer\CreatePageRequest;
use App\Http\Resources\PageResource;
use App\Models\Page;
use Illuminate\Http\Request;
use Illuminate\Support\Str;

class PageController extends Controller
{

    public function __construct()
    {
        $this->middleware('auth:writer');
    }

    public function index()
    {
        $pages = Page::belongsToUser()->select('id', 'page_name', 'slug', 'access', 'updated_at', 'book_id')
            ->paginate(10);
        return view('pages.writer.page.index')
            ->with('pages', PageResource::collection($pages));
    }

    public function create(Request $request)
    {
        $page_name = $request->get('page_name', 'Untitled Page');
        $slug = Str::slug($request->page_name);
        $page = Page::create([
            'book_id' => $request->book_id,
            'page_name' => $page_name,
            'heading' => $page_name,
            'slug' => $slug,
            'access' => 'public',
            'writer_id' => auth()->id()
        ]);
        return redirect()->route('writer.pages.edit', ['slug' => $slug, 'page' => $page->id]);
    }

    public function edit(Request $request, $slug)
    {
        if (!$request->has('page')) {
            $page = Page::where('slug', $slug)
                ->first();
            return view('pages.writer.page.edit.index')
                ->with('page', $page);
        }

        $page = Page::findOrFail($request->page);
        return view('pages.writer.page.edit.index')
            ->with('page', $page);
    }

    public function update($id, CreatePageRequest $request)
    {
        $page = Page::findOrFail($id);
        $attributes = [
            'page_name' => $request->page_name == '' ? $request->heading : $request->page_name,
            'heading' => $request->heading,
            'slug' => $request->slug,
            'description' => $request->description,
            'content' => $this->cleanContent($request->inputContent),
            'access' => $request->access,
        ];
        $page->update($attributes);
        if ($book = $page->book()->first()) {
            return redirect()->route('writer.books.detail', $book->id);
        }
        return redirect()->route('writer.pages');
    }

    public function search(Request $request)
    {
        return redirect()->route('writer.pages', ['q' => $request->search]);
    }

    public function restore($id)
    {
        Page::withTrashed()->whereId($id)->restore();
        return redirect()->route('writer.archives');
    }

    public function destroy($id)
    {
        Page::findOrFail($id)->delete();
        return redirect()->route('writer.pages');
    }

    public function forceDelete($id)
    {
        Page::withTrashed()->whereId($id)->forceDelete();
        return redirect()->route('writer.archives');
    }

}

resources/views/lists/writer/book_pages.blade.php
@isset($pages)
    <div class="kt-datatable kt-datatable--default kt-datatable--brand kt-datatable--loaded"
         id="kt_apps_user_list_datatable">
        <table class="kt-datatable__table" style="display: block; overflow-x: scroll">
            <thead class="kt-datatable__head">
            <tr class="kt-datatable__row" style="left: 0;">
                <th class="kt-datatable__cell"><span style="width: 30px;">#</span></th>
                <th class="kt-datatable__cell"><span style="width: 200px;">Page Name</span></th>
                <th class="kt-datatable__cell"><span style="width: 100px;">Access</span></th>
                <th class="kt-datatable__cell"><span style="width: 100px;">Last Updated</span></th>
                <th class="kt-datatable__cell"><span style="width: 160px">Actions</span></th>
            </tr>
            </thead>
            <tbody class="kt-datatable__body" style="">
            @if($pages->count())
                @foreach($pages as $index => $page)
                    <tr data-row="30" class="kt-datatable__row" style="left: 0;">
                        <td class="kt-datatable__cell"><span style="width: 30px;">{{ $index + $pages->firstItem() }}</span></td>
                        <td class="kt-datatable__cell">
                        <span style="width: 200px;">
                            <div class="kt-user-card-v2">
                                <div class="kt-user-card-v2__details">
                                    <a class="kt-user-card-v2__name" href="{{ route('pages.detail', ['slug' => $page->slug, 'page' => $page->id]) }}">
                                        {{ $page->page_name }}
                                    </a>
                                </div>
                            </div>
                        </span>
                        </td>
                        <td class="kt-datatable__cell">
                        <span style="width: 100px;">
                            @switch($page->access)
                                @case('public')
                                <span class="kt-badge kt-badge--success kt-badge--inline kt-badge--pill">
                                    {{ __('Public') }}
                                </span>
                                @break
                                @case('private')
                                <span class="kt-badge kt-badge--danger kt-badge--inline kt-badge--pill">
                                    {{ __('Only Me') }}
                                </span>
                                @break
                            @endswitch
                        </span>
                        </td>
                        <td class="kt-datatable__cell"><span style="width: 100px;">{{ $page->updated_at }}</span></td>
                        <td class="kt-datatable__cell">
                        <span style="width: 160px;">
                            <a style="width: 50px;" href="{{ route('pages.detail', ['slug' => $page->slug, 'page' => $page->id]) }}"
                               class="btn btn-primary text-center">
                                <i class="la la-eye"></i>
                            </a>
                            <a style="width: 50px;" href="{{ route('writer.pages.edit', ['slug' => $page->slug, 'page' => $page->id]) }}"
                               class="btn btn-success text-center">
                                <i class="la la-edit"></i>
                            </a>
                            <a href=""
                               onclick="event.preventDefault(); document.getElementById('deleteBook{{$page->id}}').submit();"
                               class="btn btn-danger text-center" style="width: 50px;"><i class="la la-trash"></i></a>
                            <form id="deleteBook{{$page->id}}"
                                  action="{{ route('writer.pages.destroy', $page->id) }}"
                                  method="POST"
                                  style="display: none;">
                                @method('DELETE')
                                @csrf
                            </form>
                        </span>
                        </td>
                    </tr>
                @endforeach
            @else
                <tr data-row="30" class="kt-datatable__row" style="left: 0;">
                    <td class="kt-datatable__cell">
                        <span class="text-center my-5">
                            @if(request()->has('q'))
                                {{ __('No results') }}
                            @else
                                {{ __('No Pages') }},
                                <a href=""
                                   onclick="event.preventDefault(); document.getElementById('addPageForm').submit();">
                                    {{ __('Create One') }}
                                </a>
                            @endif
                        </span>
                    </td>
                </tr>
            @endif
            </tbody>
        </table>
        {{ $pages->links() }}
    </div>

@endisset

resources/views/lists/writer/books.blade.php
@isset($books)

    @push('styles')
        <link rel="stylesheet" href="{{ asset('css/custom/card-list.css') }}">
    @endpush

    @if($books->count())
        <div class="card-list">
            @foreach($books as $book)
                <a href="{{ route('writer.books.detail', $book->id) }}"
                   class="card kt-portlet kt-portlet--height-fluid">
                    <img src="{{ $book->cover_image_url }}" class="w-100 img-fluid" alt="">
                    <div class="card-text">
                        <h4 class="text-dark">{{ $book->book_name }}</h4>
                        <p class="text-dark">{{ $book->description }}</p>
                        <p><small class="text-muted">Last updated on {{ $book->updated_at }}</small></p>
                    </div>
                </a>
            @endforeach
        </div>
        @if($books->hasPages())
            <div class="kt-datatable kt-datatable--default kt-datatable--brand kt-datatable--loaded"
                 id="kt_apps_user_list_datatable">
                {{ $books->links() }}
            </div>
        @endif
    @else
        @if(preg_match('/profiles/', request()->url()))
            @if($user->id == Auth::id())
                <div style="width: 100%; margin: 8rem 0; text-align: center; font-size: 1.3em;">
                    There are no books! <a href="{{ route('writer.books.create') }}">Create One</a>
                </div>
            @else
                <div style="width: 100%; margin: 8rem 0; text-align: center; font-size: 1.3em;">
                    This person haven't created any books!
                </div>
            @endif
        @else
            <div style="width: 100%; margin: 8rem 0; text-align: center; font-size: 1.3em;">
                There are no books! <a href="{{ route('writer.books.create') }}">Create One</a>
            </div>
        @endif
    @endif

@endisset

resources/views/lists/writer/pages.blade.php
@isset($pages)
    <div class="kt-datatable kt-datatable--default kt-datatable--brand kt-datatable--loaded"
         id="kt_apps_user_list_datatable">
        <table class="kt-datatable__table" style="display: block; overflow-x: scroll">
            <thead class="kt-datatable__head">
            <tr class="kt-datatable__row" style="left: 0;">
                <th class="kt-datatable__cell"><span style="width: 30px;">#</span></th>
                <th class="kt-datatable__cell"><span style="width: 200px;">Heading</span></th>
                <th class="kt-datatable__cell"><span style="width: 200px;">Book</span></th>
                <th class="kt-datatable__cell"><span style="width: 100px;">Access</span></th>
                <th class="kt-datatable__cell"><span style="width: 100px;">Last Updated</span></th>
                <th class="kt-datatable__cell"><span style="width: 160px">Actions</span></th>
            </tr>
            </thead>
            <tbody class="kt-datatable__body" style="">
            @if($pages->count())
                @foreach($pages as $index => $page)
                    <tr data-row="30" class="kt-datatable__row" style="left: 0;">
                        <td class="kt-datatable__cell"><span
                                style="width: 30px;">{{ $index + $pages->firstItem() }}</span></td>
                        <td class="kt-datatable__cell">
                <span style="width: 200px;">
                    <div class="kt-user-card-v2">
                        <div class="kt-user-card-v2__details">
                            <a class="kt-user-card-v2__name" href="{{ route('pages.detail', ['slug' => $page->slug, 'page' => $page->id]) }}">{{ $page->page_name }}</a>
                        </div>
                    </div>
                </span>
                        </td>
                        <td class="kt-datatable__cell">
                <span style="width: 200px;">
                    {{ $page->book_name }}
                </span>
                        </td>
                        <td class="kt-datatable__cell">
                <span style="width: 100px;">
                    @switch($page->access)
                        @case('public')
                        <span class="kt-badge kt-badge--success kt-badge--inline kt-badge--pill">
                            {{ __('Public') }}
                        </span>
                        @break
                        @case('private')
                        <span class="kt-badge kt-badge--danger kt-badge--inline kt-badge--pill">
                            {{ __('Only Me') }}
                        </span>
                        @break
                    @endswitch

                </span>
                        </td>
                        <td class="kt-datatable__cell"><span style="width: 100px;">{{ $page->updated_at }}</span></td>
                        <td class="kt-datatable__cell">
                <span style="width: 160px;">
                    <a href="{{ route('pages.detail', ['slug' => $page->slug, 'page' => $page->id]) }}"
                       class="btn btn-primary text-center"
                       style="width: 50px;"><i class="la la-eye"></i></a>
                    <a href="{{ route('writer.pages.edit', $page->slug) }}" class="btn btn-success text-center"
                       style="width: 50px;"><i class="la la-edit"></i></a>
                    <a href=""
                       onclick="event.preventDefault(); document.getElementById('deletePage{{$page->id}}').submit();"
                       class="btn btn-danger text-center" style="width: 50px;"><i class="la la-trash"></i></a>
                    <form id="deletePage{{$page->id}}"
                          action="{{ route('writer.pages.destroy', $page->id) }}"
                          method="POST"
                          style="display: none;">
                        @method('DELETE')
                        @csrf
                    </form>
                </span>
                        </td>
                    </tr>
                @endforeach
            @else
                <tr data-row="30" class="kt-datatable__row" style="left: 0;">
                    <td class="kt-datatable__cell">
                        <span class="text-center my-5">
                            @if(request()->has('q'))
                                {{ __('No results') }}
                            @else
                                {{ __('No Items') }}
                            @endif
                        </span>
                    </td>
                </tr>
            @endif
            </tbody>
        </table>
        {{ $pages->links() }}
    </div>
@endisset