routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Auth::routes();

Route::group([
    'domain' => 'admin.' . config('app.short_url'),
    'namespace' => 'Auth',
    'as' => 'auth.'
], function () {

    Route::get('/login', 'LoginController@showAdminLoginForm')->name('login.admin');
    Route::get('/register', 'RegisterController@showAdminRegisterForm')->name('register.admin');

});

Route::group([
    'domain' => 'admin.' . config('app.short_url'),
    'namespace' => 'Admin',
    'as' => 'admin.'
], function () {

    Route::get('/dashboard', 'DashboardController@index')->name('dashboard');

    Route::group([
        'prefix' => '/users',
        'as' => 'users.'
    ], function () {

        Route::get('/', 'UserController@index')->name('index');
        Route::post('/search', 'UserController@search')->name('search');

    });

    Route::group([
        'prefix' => '/books',
        'as' => 'books.'
    ], function () {

        Route::get('/', 'BookController@index')->name('index');
        Route::post('/search', 'BookController@search')->name('search');

    });

    Route::resource('/categories', 'CategoryController');
    Route::group([
        'prefix' => '/categories',
        'as' => 'categories.'
    ], function () {

        Route::post('/search', 'CategoryController@search')->name('search');

    });

    Route::resource('/languages', 'LanguageController');
    Route::group([
        'prefix' => '/languages',
        'as' => 'languages.'
    ], function () {

        Route::post('/search', 'LanguageController@search')->name('search');

    });

});

Route::get('/', 'HomeController@index')->name('home');
Route::get('/search', 'SearchController@index')->name('search');
Route::get('/faq', 'FaqController@index')->name('faq');
Route::get('/{slug}/read', 'PageController@index')->name('pages.detail');
Route::get('/set-language/{locale}', 'LocalizationController@setLanguage')->name('languages.set');

Route::middleware('auth:admin,writer')->get('/profiles', 'ProfileController@index')->name('profiles.index');
Route::middleware('auth:writer,admin')->get('/profiles/edit', 'ProfileController@edit')->name('profiles.edit');
Route::get('/profiles/{id}', 'ProfileController@show')->name('profiles.show');

Route::post('/search', 'SearchController@search')->name('search.form');

Route::group([
    'namespace' => 'Auth',
    'as' => 'auth.'
], function () {


    Route::post('/logout', 'LoginController@logout')->name('logout');

    Route::group([
        'prefix' => '/login',
        'as' => 'login.'
    ], function () {

        Route::get('/', 'LoginController@showWriterLoginForm')->name('writer');
        Route::post('/{role}', 'LoginController@login')->name('form');

    });

    Route::group([
        'prefix' => '/register',
        'as' => 'register.'
    ], function () {

        Route::get('/', 'RegisterController@showWriterRegisterForm')->name('writer');
        Route::post('/{role}', 'RegisterController@register')->name('form');

    });

});

Route::group([
    'namespace' => 'Auth',
    'as' => 'password.'
], function () {

    Route::get('/forgot-password', 'ForgotPasswordController@showLinkRequestForm')->name('request');
    Route::get('/reset-password/{token}', 'ResetPasswordController@showResetForm')->name('reset');

    Route::post('/password/email', 'ForgotPasswordController@sendResetLinkEmail')->name('email');
    Route::post('/password/reset', 'ResetPasswordController@reset')->name('update');

});

Route::group([
    'namespace' => 'Writer',
    'as' => 'writer.'
], function () {

    Route::get('/archives', 'ArchiveController@index')->name('archives');

    Route::get('/all-books', 'BookController@index')->name('books');
    Route::group([
        'prefix' => '/books',
        'as' => 'books.'
    ], function () {

        Route::get('/create', 'BookController@create')->name('create');
        Route::get('/{id}/edit-info', 'BookController@edit')->name('edit');
        Route::get('/{id}', 'BookController@detail')->name('detail');
        Route::get('/add-pages/{id}', 'BookController@addPages')->name('add_pages');

        Route::post('/', 'BookController@store')->name('store');
        Route::post('/search', 'BookController@search')->name('search');
        Route::put('/update/{id}', 'BookController@update')->name('update');
        Route::post('/restore/{id}', 'BookController@restore')->name('restore');
        Route::delete('/{id}', 'BookController@destroy')->name('destroy');
        Route::delete('/force-delete/{id}', 'BookController@forceDelete')->name('force_delete');

    });

    Route::get('/all-pages', 'PageController@index')->name('pages');
    Route::get('/{slug}/edit', 'PageController@edit')->name('pages.edit');
    Route::group([
        'prefix' => '/pages',
        'as' => 'pages.'
    ], function () {

        Route::post('/create', 'PageController@create')->name('create');
        Route::post('/search', 'PageController@search')->name('search');
        Route::put('/update/{id}', 'PageController@update')->name('update');
        Route::post('/restore/{id}', 'PageController@restore')->name('restore');
        Route::delete('/{id}', 'PageController@destroy')->name('destroy');
        Route::delete('/force-delete/{id}', 'PageController@forceDelete')->name('force_delete');

    });

});

Route::post('/uploads/image', 'FileUploadController@uploadImage')->name('uploads.image');

Route::fallback('ErrorController@notFound')->name('not_found');

app/Models/Language.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Carbon;

class Language extends Model
{
    protected $fillable = [
        'language_name'
    ];

    public function getUpdatedAtAttribute($updated_at)
    {
        return Carbon::parse($updated_at, config('app.timezone'))
            ->setTimezone('GMT+7')
            ->format('d M Y');
    }
}

app/Http/Controllers/Admin/LanguageController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\CreateLanguageRequest;
use App\Models\Language;
use Illuminate\Http\Request;

class LanguageController extends Controller
{

    public function __construct()
    {
        $this->middleware('auth:admin');
    }

    public function index(Request $request)
    {
        return view('pages.admin.language.index')
            ->with('languages',
                Language::where('language_name', 'like', '%' . $request->query('q', '') . '%')
                    ->paginate(10)
            );
    }

    public function create()
    {
        return view('pages.admin.language.create');
    }

    public function store(CreateLanguageRequest $request)
    {
        Language::create([
            'language_name' => $request->language_name
        ]);
        return redirect()->route('admin.languages.index');
    }

    public function show($id)
    {

    }

    public function edit($id)
    {

    }

    public function update(Request $request, $id)
    {

    }

    public function destroy($id)
    {
        Language::findOrFail($id)->delete();
        return redirect()->route('admin.languages.index');
    }

    public function search(Request $request)
    {
        return redirect()->route('admin.languages.index', ['q' => $request->search]);
    }

}

resources/views/pages/admin/language/create.blade.php
@extends('layouts.dashboard_app', [
    'page_key' => 'language-add'
])

@push('styles')
    <link rel="stylesheet" href="{{ asset('css/custom/create.css') }}">
@endpush

@section('subheader-main')
    <h3 class="kt-subheader__title"> {{ __('Create Language') }} </h3>
@stop

@section('content')
    <div class="kt-portlet">
        <div class="kt-portlet__body kt-portlet__body--fit">
            <div class="kt-grid  kt-wizard-v1 kt-wizard-v1--white" id="kt_projects_add"
                 data-ktwizard-state="step-first">
                <div class="kt-grid__item kt-grid__item--fluid kt-wizard-v1__wrapper">
                    <!--begin: Form Wizard Form-->
                    <form method="post" action="{{ route('admin.languages.store') }}" class="kt-form"
                          id="kt_projects_add_form">
                        @csrf
                        <div class="kt-wizard-v1__content">
                            <div class="kt-heading kt-heading--md">New Language:</div>
                            <div class="kt-section kt-section--first">
                                <div class="kt-wizard-v1__form">
                                    <div class="row">
                                        <div class="col-xl-12">
                                            <div class="kt-section__body">
                                                <div class="form-group row">
                                                    <label class="col-xl-3 col-lg-3 col-form-label">
                                                        Language Name
                                                    </label>
                                                    <div class="col-lg-9 col-xl-9">
                                                        <input name="language_name"
                                                               class="form-control @error('language_name') is-invalid @enderror""
                                                        type="text"
                                                        value="{{ old('language_name') }}">
                                                        @error('language_name')
                                                        <span class="invalid-feedback" role="alert">
                                                            <strong>{{ $message }}</strong>
                                                        </span>
                                                        @enderror
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <!--begin: Form Actions -->
                        <div class="kt-form__actions">
                            <button type="submit"
                                    class="btn btn-brand btn-md btn-tall btn-wide kt-font-bold kt-font-transform-u"
                                    data-ktwizard-type="action-next">
                                Create
                            </button>
                        </div>
                        <!--end: Form Actions -->
                    </form>
                    <!--end: Form Wizard Form-->
                </div>
            </div>
        </div>
    </div>
@stop

resources/views/pages/admin/language/index.blade.php
@extends('layouts.dashboard_app', [
    'page_key' => 'languages-list'
])

@section('subheader-main')
    <h3 class="kt-subheader__title"> {{ __('common.languages') }} </h3>

    <span class="kt-subheader__separator kt-subheader__separator--v"></span>

    <div class="kt-subheader__group" id="kt_subheader_search">
        <span class="kt-subheader__desc" id="kt_subheader_total"> {{ $languages->total() }} {{ __('common.languages') }} </span>

        <form method="post" action="{{ route('admin.languages.search') }}" class="kt-margin-l-20" id="kt_subheader_search_form">
            @csrf
            <div class="kt-input-icon kt-input-icon--right kt-subheader__search">
                <input name="search" type="text" class="form-control" placeholder="Search..." id="generalSearch" value="{{ request()->query('q') }}">
                <span class="kt-input-icon__icon kt-input-icon__icon--right">
                    <span> @include('icons.search') </span>
                </span>
            </div>
        </form>
    </div>
@stop

@section('subheader-toolbar')
    <a href="{{ route('admin.languages.create') }}" class="btn btn-label-brand btn-bold">
        {{ __('common.new.language') }}
    </a>
@stop

@section('content')
    <div class="kt-portlet kt-portlet--height-fluid">
        <div class="kt-portlet__body kt-portlet__body--fit">

            @include('lists.admin.languages')

        </div>
    </div>
@stop